/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Gideon Abochie (https://sketchfab.com/gabochie)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/olam-conference-room-tema-6b968fac1b64479195745b42d93aa6ef
title: Olam Conference Room- Tema
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/conferenceRoom.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI, -1.57, 0]}>
        <group position={[7202.81, -3550, 898.36]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.ALUMINIUM__FORAFORM} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.BLACK_PLASTIC__FORAFORM} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.CHROME__FORAFORM} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.CHROME__FORAFORM} />
          <mesh geometry={nodes.Object_7.geometry} material={materials['CONCRETE_-_04']} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.DARK_GREY_EPOXY__FORAFORM} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.DARK_GREY_EPOXY__FORAFORM} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.FORMICA_DARK_GREY_K1944__FORAF} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.GDLM13_OAK_VENEER} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.GDLM14_GLAS} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.GDLM15_GLAS_OPAK} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.GDLM22_DEFPICT} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.GDLM32_PICTMAT} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.GDLM35_MAT} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.GDLM37_BUILTINMATBLACKPLASTI} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.GDLM37_BUILTINMATBLACKPLASTI} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.GDLM41_BUILTINMATMACPERFORAT} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.GDLM42_BUILTINMATMACPERFORAT} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.GDLM46_FF_BLACK} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.GDLM46_FF_BLACK} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.GDLM59_CUSTOM_FABRIC1} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.GDLM59_CUSTOM_FABRIC1} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.GDLM9_BUILTINMATILLUMINATIO} />
          <mesh geometry={nodes.Object_26.geometry} material={materials['GLASS_-_BLUE']} />
          <mesh geometry={nodes.Object_27.geometry} material={materials['GLASS_-_BLUE']} />
          <mesh geometry={nodes.Object_28.geometry} material={materials['GLASS_-_CLEAR_FAST']} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.GLASS__FORAFORM} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.LEATHER_WHITE__FORAFORM} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.LEATHER_WHITE__FORAFORM} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.METALLIC_EPOXY__FORAFORM} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.METALLIC_EPOXY__FORAFORM} />
          <mesh geometry={nodes.Object_34.geometry} material={materials['METAL_-_CHROME_01']} />
          <mesh geometry={nodes.Object_35.geometry} material={materials['METAL_-_IRON']} />
          <mesh geometry={nodes.Object_36.geometry} material={materials['METAL_-_IRON']} />
          <mesh geometry={nodes.Object_37.geometry} material={materials['METAL_-_NICKEL']} />
          <mesh geometry={nodes.Object_38.geometry} material={materials['METAL_-_NICKEL']} />
          <mesh geometry={nodes.Object_39.geometry} material={materials['METAL_-_STAINLESS_STEEL']} />
          <mesh geometry={nodes.Object_40.geometry} material={materials['METAL_-_STEEL']} />
          <mesh geometry={nodes.Object_41.geometry} material={materials['METAL_-_ZINC']} />
          <mesh geometry={nodes.Object_42.geometry} material={materials['PAINT_-_ANTHRACITE']} />
          <mesh geometry={nodes.Object_43.geometry} material={materials['PAINT_-_ANTHRACITE']} />
          <mesh geometry={nodes.Object_44.geometry} material={materials['PAINT_-_DARK_GRAY']} />
          <mesh geometry={nodes.Object_45.geometry} material={materials['PAINT_-_GLOSSY_WHITE']} />
          <mesh geometry={nodes.Object_46.geometry} material={materials['PAINT_-_GOLDEN_BEIGE']} />
          <mesh geometry={nodes.Object_47.geometry} material={materials['PAINT_-_IVORY_BLACK']} />
          <mesh geometry={nodes.Object_48.geometry} material={materials['PAINT_-_IVORY_BLACK']} />
          <mesh geometry={nodes.Object_49.geometry} material={materials['PAINT_-_LIGHT_GRAY']} />
          <mesh geometry={nodes.Object_50.geometry} material={materials['PAINT_-_TITANIUM_WHITE']} />
          <mesh geometry={nodes.Object_51.geometry} material={materials['PAINT_-_TITANIUM_WHITE']} />
          <mesh geometry={nodes.Object_52.geometry} material={materials['PAINT_-_VERMILION']} />
          <mesh geometry={nodes.Object_53.geometry} material={materials['PAINT_-_VERMILION']} />
          <mesh geometry={nodes.Object_54.geometry} material={materials['PLASTIC_-_LAMINATE']} />
          <mesh geometry={nodes.Object_55.geometry} material={materials['PLASTIC_-_LAMINATE']} />
          <mesh geometry={nodes.Object_56.geometry} material={materials['STUCCO_-_WHITE_FINE']} />
          <mesh geometry={nodes.Object_57.geometry} material={materials['STUCCO_-_WHITE_ROUGH']} />
          <mesh geometry={nodes.Object_58.geometry} material={materials['TILES_-_TAN_30X30']} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.TOP_FROSTED_GLASS__FORAFORM} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.VARIER_CHROME} />
          <mesh geometry={nodes.Object_61.geometry} material={materials.VARIER_OAK_BLACK_LACQUERED} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.VARIER_OAK_BLACK_LACQUERED} />
          <mesh geometry={nodes.Object_63.geometry} material={materials.VARIER_OILED} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.WHITE_EPOXY__FORAFORM} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.WHITE_EPOXY__FORAFORM} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.WHITE_EPOXY__RAL9010___FORAFOR} />
          <mesh geometry={nodes.Object_67.geometry} material={materials.WHITE_LACQUERED_BEECH__FORAFOR} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.WHITE_LACQUERED_BEECH__FORAFOR} />
          <mesh geometry={nodes.Object_69.geometry} material={materials['WHITE__NCS_S_0500-N___FORAFORM']} />
          <mesh geometry={nodes.Object_70.geometry} material={materials['WHITE__NCS_S_0500-N___FORAFORM']} />
          <mesh geometry={nodes.Object_71.geometry} material={materials['WOOD_-_PINE_GRAINED_VERTICAL']} />
          <mesh geometry={nodes.Object_72.geometry} material={materials['WOOD_-_WALNUT_HORIZONTAL']} />
          <mesh geometry={nodes.Object_73.geometry} material={materials['WOOD_-_WALNUT_HORIZONTAL']} />
          <mesh geometry={nodes.Object_74.geometry} material={materials['WOOD_-_WALNUT_VERTICAL']} />
          <mesh geometry={nodes.Object_75.geometry} material={materials['WOOD_-_WALNUT_VERTICAL']} />
          <mesh geometry={nodes.Object_76.geometry} material={materials['METAL_-_ALUMINIUM']} />
          <mesh geometry={nodes.Object_77.geometry} material={materials['METAL_-_ALUMINIUM']} />
          <mesh geometry={nodes.Object_78.geometry} material={materials['METAL_-_ZINC']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/conferenceRoom.glb')
