/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: fizzlefreshh (https://sketchfab.com/fizzlefreshh)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/office-blender-cycles-bake-3651ffe6b9f14ceeb0f33f20d3e89a2b
title: Office - Blender Cycles Bake
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/office-scene.glb')

  return (
    <group ref={group} {...props} dispose={null} position={[0, 0, 10]} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.71}>
        <group position={[2.57, -4.22, 1.41]} rotation={[0, 0, -Math.PI]}>
          <mesh geometry={nodes.door2_0.geometry} material={materials.door_bake} />
        </group>
        <group position={[0, 0, 1.29]}>
          <mesh geometry={nodes.Cube_0.geometry} material={materials.desk_baked} />
        </group>
        <group position={[-0.4, -2.27, 0.02]}>
          <mesh geometry={nodes.Plane_0.geometry} material={materials.walls_msall_baked} />
        </group>
        <group position={[-0.49, 0.05, 1.72]} rotation={[1.45, 0, 0]}>
          <mesh geometry={nodes.Cube006_0.geometry} material={materials.monitor_bake} />
        </group>
        <group position={[0.31, -0.01, 1.62]}>
          <mesh geometry={nodes.Cube009_0.geometry} material={materials.computer_bake} />
        </group>
        <group position={[-0.34, -0.23, 1.31]}>
          <mesh geometry={nodes.Cube024_0.geometry} material={materials.keyboard_plus_baked} />
        </group>
        <group position={[0.73, 1.07, 1.87]} rotation={[Math.PI / 2, 0, 0]} scale={7.54}>
          <mesh geometry={nodes.Plane008_0.geometry} material={materials.emit_white} />
        </group>
        <group position={[2.61, -1.09, 1.4]}>
          <mesh geometry={nodes.Cube036_0.geometry} material={materials.plants_bake} />
        </group>
        <group position={[-1.99, 0.04, 0.23]}>
          <mesh geometry={nodes.Cylinder_0.geometry} material={materials.chair_headphone_bin_baked} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/office-scene.glb')
